namespace: "vulnerscom"
name: "vulners_ansible_plugin"
version: "0.0.1"
readme: "README.md"
authors:
    - "vankyver (https://github.com/vankyver)"
    - "GMedian"
license:
    - "GPL-3.0-only"
tags:
    - security
repository: "https://github.com/vulnersCom/vulners-ansible"
build_ignore:
    - test
    - template
    - .gitignore
    - '*.env'
